setup:
	sudo bundle install
	brew install swiftgen
	brew install mint
	mint run xcodegen generate
	bundle exec pod install

brew:
	brew install swiftgen
	brew install mint

generate:
	mint run xcodegen generate
	bundle exec pod install
