name: Demo
attributes:
  LastUpgradeCheck: 1160
  ORGANIZATIONNAME: "fromkk"
options:
  bundleIdPrefix: me.fromkk
  deploymentTarget:
    iOS: 13.0
configs:
  Debug: debug
  Release: release
schemes:
  Demo-dev:
    build:
      targets:
        Demo-dev: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: DemoTests
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
      revealArchiveInOrganizer: false
  Demo:
    build:
      targets:
        Demo: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: false
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 13.0
    TARGETED_DEVICE_FAMILY: 1,2
    SWIFT_VERSION: 5.0
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
settingGroups:
  appBaseSettings:
    DEVELOPMENT_TEAM: K84E4S7G4C
targets:
  Demo-dev:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    sources:
      - path: Sources
        name: Sources
    preBuildScripts:
      - script: swiftgen
        name: SwiftGen
      - script: "${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat $SRCROOT --disable trailingCommas --exclude Pods,Demo/Assets"
        name: SwiftFormat
      - script: "${PODS_ROOT}/SwiftLint/swiftlint"
        name: SwiftLint
    settings:
      groups:
        - appBaseSettings
      base:
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        INFOPLIST_FILE: Sources/Demo-dev-Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        GCC_PREPROCESSOR_DEFINITIONS: $(inherited) DEBUG=1
        ENABLE_TESTABILITY: YES
        PRODUCT_MODULE_NAME: Demo
        PRODUCT_BUNDLE_IDENTIFIER: me.fromkk.BitriseDemo.dev
        OTHER_LDFLAGS:
          - $(inherited)
          - $(OTHER_LDFLAGS)
          - -ObjC
      configs:
        Debug:
          CODE_SIGN_IDENTITY: Apple Development
          DEVELOPMENT_TEAM: K84E4S7G4C
          PROVISIONING_PROFILE_SPECIFIER: Bitrise iOS development - (me.fromkk.BitriseDemo.dev)
        Release:
          CODE_SIGN_IDENTITY: Apple Development
          DEVELOPMENT_TEAM: K84E4S7G4C
          PROVISIONING_PROFILE_SPECIFIER: Bitrise iOS development - (me.fromkk.BitriseDemo.dev)
  Demo:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    sources:
      - path: Sources
        name: Sources
    preBuildScripts:
      - script: swiftgen
        name: SwiftGen
      - script: "${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat $SRCROOT --disable trailingCommas --exclude Pods,Demo/Assets"
        name: SwiftFormat
      - script: "${PODS_ROOT}/SwiftLint/swiftlint"
        name: SwiftLint
    settings:
      groups:
        - appBaseSettings
      base:
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        INFOPLIST_FILE: Sources/Demo-Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GCC_PREPROCESSOR_DEFINITIONS: $(inherited)
        PRODUCT_BUNDLE_IDENTIFIER: me.fromkk.BitriseDemo
        OTHER_LDFLAGS:
          - $(inherited)
          - $(OTHER_LDFLAGS)
          - -ObjC
      configs:
        Debug:
          CODE_SIGN_IDENTITY: Apple Distribution
          DEVELOPMENT_TEAM: K84E4S7G4C
          PROVISIONING_PROFILE_SPECIFIER: Bitrise ios ad-hoc - (me.fromkk.BitriseDemo)
        Release:
          CODE_SIGN_IDENTITY: Apple Distribution
          DEVELOPMENT_TEAM: K84E4S7G4C
          PROVISIONING_PROFILE_SPECIFIER: Bitrise ios ad-hoc - (me.fromkk.BitriseDemo)
  DemoTests:
    type:  bundle.unit-test
    platform: iOS
    sources: [DemoTests]
    scheme: {}
    dependencies:
      - target: Demo-dev
    settings:
      CLANG_ENABLE_MODULES: YES
      DEVELOPMENT_TEAM: XE9C97EHP4
      INFOPLIST_FILE: "DemoTests/Info.plist"
